### ISSUE TITLE
Failed to determine wireless interface

### ISSUE THREAD

**Issue by loskiq** [vanhoefm/krackattacks-test-ap-ft#11]
```
root@pi3:~/krackattacks-test-ap-ft# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.10.0.8  netmask 255.255.255.0  broadcast 10.10.0.255
        inet6 fe80::9263:99c9:27f0:57d1  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:a4:28:32  txqueuelen 1000  (Ethernet)
        RX packets 3027  bytes 1064986 (1.0 MiB)
        RX errors 0  dropped 3  overruns 0  frame 0
        TX packets 3399  bytes 747832 (730.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether b8:27:eb:f1:7d:67  txqueuelen 1000  (Ethernet)
        RX packets 5  bytes 739 (739.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18  bytes 2362 (2.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@pi3:~/krackattacks-test-ap-ft# ./krack-ft-test.py wlan0 loskiq --target 6C:3B:6B:14:57:61
[10:02:29] Failed to determine wireless interface. Specify one using the -i parameter.
root@pi3:~/krackattacks-test-ap-ft#
```

What am I doing wrong?

**Comment by Endagegnehu** [comment]
I think you should add -i in front of you wireless adapter name

**Comment by loskiq** [comment]
@Endagegnehu Thank you. But now there is another mistake. Command `ifconfig wlan0 down` does not help

```
root@pi3:~/krackattacks-test-ap-ft# ./krack-ft-test.py -i wlan0 loskiq --target 6C:3B:6B:14:57:61
[10:28:42] Note: disable Wi-Fi in your network manager so it doesn't interfere with this script
command failed: Operation not supported (-95)
Traceback (most recent call last):
  File "./krack-ft-test.py", line 338, in <module>
    attack.run()
  File "./krack-ft-test.py", line 286, in run
    self.configure_interfaces()
  File "./krack-ft-test.py", line 277, in configure_interfaces
    subprocess.check_output(["iw", self.nic_iface, "interface", "add", self.nic_mon, "type", "monitor"])
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['iw', 'wlan0', 'interface', 'add', 'wlan0mon', 'type', 'monitor']' returned non-zero exit status 161
[10:28:42] Closing wpa_supplicant and cleaning up ...
root@pi3:~/krackattacks-test-ap-ft#
```

**Comment by Endagegnehu** [comment]
Did you disabled hardware encryption engine of the WiFi NICs if you did not
try ./disable-hwcrypto.sh

**Comment by vanhoefm** [comment]
Read the readme. First execute the script using `./krack-ft-test.py --help` and then follow the instructions.
